# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    cd projects/react-static-website
    yarn
  displayName: 'isntall node modules'

# - script: |
#     yarn test
#   displayName: 'run unit tests'

- script: |
    cd projects/react-static-website
    yarn test
    yarn build
  displayName: 'run test and build'


- script: |
    pwd
    ls
  displayName: 'check if retains the dir from last script'
