trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script : sudo apt-get install build-essential

- script : cd projects/react-static-website
  displayName: 'change workdirectory to project'

- script: yarn 
  displayName: 'Installing node modules'

- script: yarn lint
  displayName: 'Checking for lint errors'

- script: |
    yarn build
  displayName: 'Running webpack build'
