# This sets trigger to any update in master  
trigger:
- master

#  Defines the host for agent (MS hosted)
pool:
  vmImage: 'ubuntu-latest'

#  Build steps for the pipeline
steps:
- script: yarn 
  workingDirectory: $(Agent.BuildDirectory)/s/projects/react-static-website
  displayName: 'Installing node modules'

- script: yarn lint
  workingDirectory: $(Agent.BuildDirectory)/s/projects/react-static-website
  displayName: 'Checking for lint errors'

- script: |
    yarn build
  workingDirectory: $(Agent.BuildDirectory)/s/projects/react-static-website
  displayName: 'Running webpack build'