trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: yarn 
  workingDirectory: $(Agent.BuildDirectory)/s/projects/react-static-website
  displayName: 'Installing node modules'

- script: yarn lint
  workingDirectory: $(Agent.BuildDirectory)/s/projects/react-static-website
  displayName: 'Checking for lint errors'

- script: |
    yarn build
  workingDirectory: $(Agent.BuildDirectory)/s/projects/react-static-website
  displayName: 'Running webpack build'
