trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# - script : sudo apt-get install build-essential

# - script : cd projects/react-static-website
#   displayName: 'change workdirectory to project'

- script: pwd 
  displayName: 'path of default directory'

- script: ls 
  displayName: 'items in  default directory'

- script: ls 
  workingDirectory: $(Agent.BuildDirectory)/s/projects/react-static-website
  displayName: 'check items in $(Agent.BuildDirectory)/projects/react-static-website'

- script: yarn 
  workingDirectory: $(Agent.BuildDirectory)/projects/react-static-website
  displayName: 'Installing node modules'

- script: yarn lint
  workingDirectory: $(Agent.BuildDirectory)/projects/react-static-website
  displayName: 'Checking for lint errors'

- script: |
    yarn build
  workingDirectory: $(Agent.BuildDirectory)/projects/react-static-website
  displayName: 'Running webpack build'
